# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &EDI
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: EDIMSP    # this changed from ap

        # ID to load the MSP definition as
        ID: EDIMSP

        MSPDir: ../organizations/peerOrganizations/EDI.hlfcards.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('EDIMSP.admin', 'EDIMSP.peer', 'EDIMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('EDIMSP.admin', 'EDIMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('EDIMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('EDIMSP.peer')"
